version: "3.9"

services:
  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
    - 127.0.0.1:9000:9000
    volumes:
    - minio-data:/data
    restart: on-failure

  api:
    build: .
    environment:
      PORT: 8080
      MINIO_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_ENDPOINT: minio:9000
      MINIO_DISABLE_SSL: "true"
    ports:
    - 127.0.0.1:8080:8080
    depends_on:
      - minio
    restart: on-failure

volumes:
  minio-data: